## 
## Travis 
sudo: false
language: cpp
compiler: g++
os:
  - linux
  - osx

# Setup repos etc before installation
before_install:
  - source ./test/travis/env.sh

install:
  - source ./test/travis/setup.sh
# command to run tests 
script:
  - cmake --version
  - cmake .
  - make
  - ls test/bin/*
  - cd ./test/bin
  - ./cpptest
  - ./lua51
  - ./lua53
