language: cpp
compiler: 
  - g++ 
  - clang
os:
  - linux
  - osx

matrix:
  - os: linux
    before_install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo apt-get update -qq
  - os: linux
    install:
      - sudo apt-get install -qq cmake
      - sudo apt-get install -qq g++-4.8
      - export CXX="g++-4.8"
script:
  - cmake --version
  - cmake .
  - make
  - ls test/bin/*
  - cd ./test/bin
  - ./cpptest
  - ./lua51
  - ./lua53
